name: Container Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build test image
        env:
          TARGET: test
        run: docker-compose -f docker-compose.yml build
      - name: Deploy test image
        env:
          TARGET: test
        run: docker-compose -f docker-compose.yml up -d

      - name: Analyze
        run: |
          docker container exec myapp.app flake8 -v
          docker container exec myapp.app mypy myapp
      - name: Unit test
        run: docker container exec myapp.app pytest
      - name: Prework for Scan
        run: docker save -o myapp.app.tar myapp.app:local
      - name: Scan Medium,Low (ignore)
        uses: aquasecurity/trivy-action@master
        with:
          input: /github/workspace/myapp.app.tar
          severity: "MEDIUM,LOW"
      - name: Scan Critical,High (exit with error)
        uses: aquasecurity/trivy-action@master
        with:
          input: /github/workspace/myapp.app.tar
          severity: "CRITICAL,HIGH"
          exit-code: "1"

      - name: Build production image
        env:
          TARGET: production
        run: |
          docker-compose -f docker-compose.yml build
          docker image tag myapp.app:local ${{ secrets.DOCKERHUB_USERNAME }}/myapp.app:${{ github.sha }}
          docker image tag myapp.db:local ${{ secrets.DOCKERHUB_USERNAME }}/myapp.db:${{ github.sha }}
      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push production image
        run: |
          docker image push ${{ secrets.DOCKERHUB_USERNAME }}/myapp.app:${{ github.sha }}
          docker image push ${{ secrets.DOCKERHUB_USERNAME }}/myapp.db:${{ github.sha }}
